ARDUINO_LIBS = Watch Adafruit_GFX RTClib Wire Wire/utility
BOARD_TAG=lilypad328

ARDMK_DIR=/usr/local/arduino-mk
ARDUINO_DIR=/usr/local/arduino
ARDUINO_PORT=/dev/ttyU?

include $(ARDMK_DIR)/Arduino.mk
